#Fibonacci Numbers: The Fibonacci sequence of numbers begins 1, 1, 2, 3, 5, 8, etc. Each term after
#the two initial 1s is generated by adding together the two terms that precede it. For example,
#1+1=2, 1+2=3, 2+3=5, and so on. Initialize a 20-element list, then use a loop to generate the
#first 20 terms in the Fibonacci sequence.

seqn=[0,1,1] + [0]*18

for pos in range(3,20):
    seqn[pos]= seqn[(pos-1)] + seqn[(pos-2)]

print(seqn[1:20])

    
    
    
    